const HO_CHI_MINH_WARDS = [
  "An Khánh",
  "An Lạc",
  "An Lạc A",
  "An Phú",
  "An Phú Đông",
  "An Sơn",
  "An Thới Đông",
  "An Thạnh",
  "Ba Tri",
  "Bà Rịa",
  "Bàn Cờ",
  "Bến Cát",
  "Bến Nghé",
  "Bến Thành",
  "Bình Hưng",
  "Bình Hưng Hòa",
  "Bình Hưng Hòa A",
  "Bình Hưng Hòa B",
  "Bình Lợi Trung",
  "Bình Mỹ",
  "Bình Tân",
  "Bình Thạnh",
  "Bình Trị Đông",
  "Bình Trị Đông A",
  "Bình Trị Đông B",
  "Bình Trưng Đông",
  "Bình Trưng Tây",
  "Cát Lái",
  "Cầu Kho",
  "Cầu Ông Lãnh",
  "Cô Giang",
  "Đa Kao",
  "Đông Hưng Thuận",
  "Gò Vấp",
  "Hiệp Bình Chánh",
  "Hiệp Bình Phước",
  "Hiệp Phú",
  "Khánh Hội",
  "Linh Chiểu",
  "Linh Đông",
  "Linh Tây",
  "Linh Trung",
  "Long Bình",
  "Long Phước",
  "Long Thạnh Mỹ",
  "Long Trường",
  "Nhiêu Lộc",
  "Phú Hữu",
  "Phú Mỹ",
  "Phước Long A",
  "Phước Long B",
  "Sài Gòn",
  "Tam Bình",
  "Tam Phú",
  "Tăng Nhơn Phú A",
  "Tăng Nhơn Phú B",
  "Tân Định",
  "Tân Hưng Thuận",
  "Thạnh Mỹ Lợi",
  "Thảo Điền",
  "Thủ Thiêm",
  "Trường Thạnh",
  "Trường Thọ",
  "Xóm Chiếu",
  "Xuân Hòa",
];

export default HO_CHI_MINH_WARDS;
